github: [mennashalabyML]   # لو عندك GitHub Sponsors
ko_fi: menna               # لو عندك حساب Ko-fi
buy_me_a_coffee: menna     # لو عندك حساب BuyMeACoffee
custom: ['https://www.upwork.com/freelancers/~menna', 'https://mostaql.com/u/menna']
